/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OSWB;

import Entities.InventoryManager;
import Entities.Item;
import Entities.PurchaseOrder;
import Entities.SalesData;
import Entities.StockReportData;
import java.text.DecimalFormat;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chieu
 */
public class IM_REPORT extends javax.swing.JFrame {
    
    
    private InventoryManager manager;
    /**
     * Creates new form IM_REPORT
     */
    public IM_REPORT() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Add this line
    }
    
    public IM_REPORT(String manager, String startDate, String endDate, StockReportData reportData) {
        initComponents();
        populateReport(manager, startDate, endDate, reportData);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Add this line
    }
    
    
    private void populateReport(String manager, String startDate, String endDate, StockReportData reportData) {
        DecimalFormat df = new DecimalFormat("#.##");

        // Set labels
        jLabel1.setText("Stock Report - " + startDate + " to " + endDate);
        jLabel2.setText("Generated By: " + manager);
        jLabel3.setText("Total Stock In Value: $" + df.format(
            reportData.getStockInValue().values().stream().mapToDouble(Double::doubleValue).sum()));
        jLabel4.setText("Total Stock Out Value: $" + df.format(
            reportData.getStockOutValue().values().stream().mapToDouble(Double::doubleValue).sum()));

        // Populate Stock In Table
        DefaultTableModel stockInModel = new DefaultTableModel(
            new String[]{"Item Code", "Quantity", "Supplier Code", "Date", "Payment Amount"}, 0);
        stockInTable.setModel(stockInModel);
        for (PurchaseOrder po : reportData.getStockInPOs()) {
            stockInModel.addRow(new Object[]{
                po.getItemCode(),
                po.getQuantity(),
                po.getSupplierCode(),
                po.getRequiredDate(),
                df.format(po.getPaymentAmount())
            });
        }

        // Populate Stock Out Table
        DefaultTableModel stockOutModel = new DefaultTableModel(
            new String[]{"Item Code", "Quantity Sold", "Retail Price", "Date", "Total Amount"}, 0);
        stockOutTable.setModel(stockOutModel);
        for (SalesData sales : reportData.getStockOutSales()) {
            stockOutModel.addRow(new Object[]{
                sales.getItemCode(),
                sales.getQuantitySold(),
                df.format(sales.getRetailPrice()),
                sales.getDate(),
                df.format(sales.getTotalAmount())
            });
        }

        // Populate Inventory Summary Table
        DefaultTableModel summaryModel = new DefaultTableModel(
            new String[]{"Item Code", "Item Name", "Current Stock", "Stock In", "Stock Out", "Net Change", "Updated Stock"}, 0);
        inventorySummaryTable.setModel(summaryModel);
        for (Item item : reportData.getInventoryItems()) {
            if (item != null) {
                String itemCode = item.getItemCode();
                int currentStock = item.getStockLevel();
                int stockIn = reportData.getStockInQty().getOrDefault(itemCode, 0);
                int stockOut = reportData.getStockOutQty().getOrDefault(itemCode, 0);
                int netChange = stockIn - stockOut;
                int updatedStock = currentStock + netChange;
                summaryModel.addRow(new Object[]{
                    itemCode,
                    item.getItemName(),
                    currentStock,
                    stockIn,
                    stockOut,
                    netChange,
                    updatedStock
                });
            }
        }

        // Ensure tables are repainted
        stockInTable.repaint();
        stockOutTable.repaint();
        inventorySummaryTable.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stockOutTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        stockInTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        inventorySummaryTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Stock Report ");

        jLabel2.setText("Generated By: ");

        jLabel3.setText("Total Stock In Value: ");

        jLabel4.setText("Total Stock Out Value: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel5.setText("Stock In ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel6.setText("Stock Out ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel7.setText("Inventory Summary");

        stockOutTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(stockOutTable);

        stockInTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(stockInTable);

        inventorySummaryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(inventorySummaryTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IM_REPORT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IM_REPORT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IM_REPORT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IM_REPORT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IM_REPORT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable inventorySummaryTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable stockInTable;
    private javax.swing.JTable stockOutTable;
    // End of variables declaration//GEN-END:variables
}
